'''
TODO:
1. klayswap 컨트랙트 추가 및 다른 dex 서비스 자산 연동
2. WKLAY를 사용하는 서비스가 추가되고 각 WKLAY 주소가 다를 시
 -> POOL_CONTRACT_ADDRESS, TOKEN_PRICE 데이터 구조 변경 필요
3. dex 서비스외에 다른 서비스들은 어떻게 연동할지 고민
'''
SERVICE_LIST = {
    'klayswap': 'KLAY',
    'pala': 'WKLAY',
}
POOL_CONTRACT_ADDRESS = {
    'klayswap': {
        'KLAY-KSP': '0x34cf46c21539e03deb26e4fa406618650766f3b9',
        'KLAY-KUSDT': '0xd83f1b074d81869eff2c46c530d7308ffec18036',
        'KSP-KUSDT': '0xe75a6a3a800a2c5123e67e3bde911ba761fe0705',
        'KSP-KDAI': '0x64e58f35e9d4e2ab6380908905177ce150aa8608', # TokenHistory API 사용하면 버그 (KAS 팀에 수정 요청함)
        'KUSDT-KDAI': '0xc320066b25b731a11767834839fe57f9b2186f84'
    },
    'pala': {
        # 2. WKLAY를 사용하는 서비스가 추가되고 각 WKLAY 주소가 다를 시 (혹은 이와 같은 경우)
        # 'PALA-KUSDT': {
        #     'LP_ADDRESS': '0x2caa83af6bbf61dc15e7bcc5952bbb554358ad11',
        #     'PALA': '',
        #     'KUSDT': '',
        # },
        'PALA-KUSDT': '0x2caa83af6bbf61dc15e7bcc5952bbb554358ad11',
        'WKLAY-PALA': '0xc556be31d170ca00241231371e139c8e4c0fc204',
        'KETH-KUSDT': '0x4755cb2bf13cf07a00368ae4a2ea4de2eb1dc1a6',
        'WKLAY-KUSDT': '0xab47edf354348e14cfcc1949b38bf2317d510b79',
        'KXRP-KUSDT': '0xf1b48634169018bd5b02906d77c8c9b738a87bcb',
        'KDAI-KUSDT': '0xa82d38cac00511509390a6f25473882d3393edaa',
        'KWBTC-KUSDT': '0x2d2926ac369e5b1d32e56d0fbbc7471ee29a8bcd',
        'KUSDC-KUSDT': '0x27ffa35d4e2443c734e25b34bbb8ef217356cf85',
        'KBNB-KUSDT': '0x369e840bd79a291f2640d63fb60ac032c894f2b7',
    }
}

TOKEN_ADDRESS = {
    'KSP': '0xc6a2ad8cc6e4a7e08fc37cc5954be07d499e7654',
    'KDAI': '0x5c74070fdea071359b86082bd9f9b3deaafbe32b',
    'KUSDT': '0xcee8faf64bb97a73bb51e115aa89c17ffa8dd167',
    'PALA': '0x7a1cdca99fe5995ab8e317ede8495c07cbf488ad',
    #WKLAY도 KLAY 취급해도 될 듯? 해당 심볼 사용하는게 하나가 아니다
    'WKLAY': '0x2ff5f6de2287ca3075232127277e53519a77947c',
    'KETH': '0x34d21b1e550d73cee41151c77f3c73359527a396',
    'KXRP': '0x9eaefb09fe4aabfbe6b1ca316a3c36afc83a393f',
    'KWBTC': '0x16d0e1fbd024c600ca0380a4c5d57ee7a2ecbf9c',
    'KUSDC': '0x754288077d0ff82af7a5317c7cb8c444d421d103',
    'KBNB': '0x574e9c26bda8b95d7329505b4657103710eb32ea',
}


# POOL_CONTRACT_ADDRESS = {
#     'klayswap': {
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#         'aaaaaa': 'aaaaaaa',
#     }
# }